# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22a7c450f8d0b72fc8b65da44b4aa492258d79e2223bf3695f316e2dea8a3aa88dd7d91fa7735d6b257a22f8625ef82b71ccae4bcb8fc57e9a98d288e7325429

test:
  secret_key_base: ba733dcdabf5acea2bc4c1a3924b29b83b6aa69e9f8e24815f3b067f6b2f2206ae2362a714f1f8a1196148b4b1657db29251fc2276d38e2d5e688e13ea137bbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
